name: .NET Core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

env:
  solution: ./src/DurableTask.Hosting.sln
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.300

    - name: Install dependencies
      run: dotnet restore $solution

    - name: Nbgv
      id: nbgv
      uses: aarnott/nbgv@v0.3

    - name: Build ${{ steps.nbgv.outputs.CloudBuildNumber }}
      run: dotnet build $solution --configuration Release --no-restore
      
    - name: Test
      run: dotnet test $solution --configuration Release --no-build

    - name: Pack
      run: dotnet pack $solution --configuration Release --no-build

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: pkg.${{ steps.nbgv.outputs.CloudBuildNumber }}
        path: ./out/pkg

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.300
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API }}

    - name: Nbgv
      id: nbgv
      uses: aarnott/nbgv@v0.3

    - name: Download pkg
      uses: actions/download-artifact@v1
      with:
        name: pkg.${{ steps.nbgv.outputs.CloudBuildNumber }}

    - name: Unzip pkg
      run: unzip pkg.${{ steps.nbgv.outputs.CloudBuildNumber }}

    - name: Upload Release Artifacts
      uses: csexton/release-asset-action@v2
      with:
        pattern: "pkg.${{ steps.nbgv.outputs.CloudBuildNumber }}/*"
        github-token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Push Nuget
    #   run: dotnet nuget push pkg..${{ steps.nbgv.outputs.CloudBuildNumber }}/*.nupkg
