name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

env:
  solution: ./src/DurableTask.Hosting.sln
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.300

    - name: Install dependencies
      run: dotnet restore $solution
      
    - name: Build
      run: dotnet build $solution --configuration Release --no-restore
      
    - name: Test
      run: dotnet test $solution --no-restore --verbosity normal

    - if: github.event_name == 'release'
    - name: Pack
      run: dotnet pack $solution --no-restore

    - if: github.event_name == 'release'
    - name: Zip
      run: zip -r out/pkg.zip ./out/pkg/

    - if: github.event_name == 'release'
      name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1

    - if: github.event_name == 'release'
      name: Upload Release Artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./out/pkg.zip
